name: 'custom-actions'
description: 'Get the dependencies (via npm) & cache them'
inputs: 
 caching:
 description: 'Whether to cache dependencies or not'
 required: true
 default: 'true'
outputs:
 used-cache:
 description: 'Whether the cache was used'
  value: ${{ steps.install.output.cache}} 
runs: 
 using: "composite"
 steps: 
  - name: cache dependencies
    id: cache
    if: ${{inputs.caching == 'true'}}
    uses: actions/cache@v3
    with:
     path: ~/.npm
     key: |
      deps-node-modules-${{ hashFiles('package-lock.json') }}
      deps-node-modules-${{ hashFiles('package.json') }}
  - name: Install dependencies
    id: install
    if: ${{ steps.cache.output.cache-hit != 'true' || inputs.caching != true}} 
    run: npm ci
    run: echo "cache = ${{ inputs.caching }}" >> $GITHUB_OUTPUT
    shell: bash
  - name: output information
    run: echo "cache used? ${{ step.cache.outputs.used-cache }}"   