name: reusable-workflow
on: 
 push:
  branches: master
 workflow_call:
  inputs:
   my-artifacts: 
     required: false
     default: my-artifacts
     type: string 
jobs:
 deploy: 
  runs-on: ubuntu-latest
  steps:
  - name: Get-Code
    uses: actions/checkout@v3
  - name: upload artifacts  
    uses: actions/upload-artifact@v3
    with: 
     name: my-artifacts
     path: my-artifacts  
    
  - name: Install dependencies
    run: npm ci
  - name: deploy
    run: echo "Deploying..."
