name: reusable-workflow
on: 
 push:
  branches: master
 workflow_call:
  inputs:
   artifact-name: 
     required: false
     default: 'my-artifacts'
     type: string 
jobs:
 deploy: 
  runs-on: ubuntu-latest
  
  steps:
  
  - name: Pass the received secret to an action
    uses: ./.github/actions/my-action
    with:
       run: ${{ inputs.artifact-name }}
  
  - name: Get-Code
    uses: actions/checkout@v3  
    
  - name: Install dependencies
    run: npm ci
  - name: deploy
    run: echo "Deploying..."
